# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortolaApp < Formula
  desc ""
  homepage "https://github.com/portolanetwork/portola"
  version "0.7.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/portolanetwork/portola-release/releases/download/v0.7.3/portola_Darwin_x86_64.tar.gz"
    sha256 "ecbf89988b3be98808274c815b08499290d586ce6f2701006234d69cc9b78b3d"

    def install
      bin.install "portd"
      bin.install "portctl"
      prefix.install Dir["cmd/portd/deployment-assets/prod-usw1/resources"]
      prefix.install "cmd/portd/deployment-assets/prod-usw1/deployment.yaml"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/portolanetwork/portola-release/releases/download/v0.7.3/portola_Darwin_arm64.tar.gz"
    sha256 "53604f26f4ccf9184b4a81d26c16d09434dce28110d8a5a9fb292cf5ee9487ef"

    def install
      bin.install "portd"
      bin.install "portctl"
      prefix.install Dir["cmd/portd/deployment-assets/prod-usw1/resources"]
      prefix.install "cmd/portd/deployment-assets/prod-usw1/deployment.yaml"
    end
  end

  def caveats
    <<~EOS
      ****************************************************************
      Installed Portola Staging Formula. To start the service run:
        brew services start portola.app
      ****************************************************************
    EOS
  end

  service do
    run [opt_bin/"portd", "service", "start"]
    environment_variables(
      "BREW_APP_FORMULA_NAME" => "portola.app",
      "BREW_APP_BIN_PATH" => "#{bin}",
      "BREW_APP_OPT_HOME" => "#{opt_prefix}",
      "BREW_PREFIX" => "#{HOMEBREW_PREFIX}"
    )
    keep_alive true
    log_path "#{var}/log/portola.app/portd.out.log"
    error_log_path "#{var}/log/portola.app/portd.err.log"
    process_type :interactive
    working_dir opt_prefix
  end
end
