# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortolaApp < Formula
  desc ""
  homepage "https://github.com/portolanetwork/portola"
  version "0.7.269"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/portolanetwork/portola-release/releases/download/v0.7.269/portola_Darwin_x86_64.tar.gz"
    sha256 "40671e1f037782ef8238ee4c226db1865a3835b04716cb0dbfcfcb4c74778471"

    def install
      bin.install "portd"
      bin.install "portctl"
      prefix.install Dir["cmd/portd/deployment-assets/prod-usw1/resources"]
      prefix.install "cmd/portd/deployment-assets/prod-usw1/deployment.yaml"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/portolanetwork/portola-release/releases/download/v0.7.269/portola_Darwin_arm64.tar.gz"
    sha256 "9e48a2e384d017573af206bff2671faca046e77914af48fc89a131104183066d"

    def install
      bin.install "portd"
      bin.install "portctl"
      prefix.install Dir["cmd/portd/deployment-assets/prod-usw1/resources"]
      prefix.install "cmd/portd/deployment-assets/prod-usw1/deployment.yaml"
    end
  end

  def caveats
    <<~EOS
      ****************************************************************
      Installed Portola Staging Formula. To start the service run:
        brew services start portola.app
      ****************************************************************
    EOS
  end

  service do
    run [opt_bin/"portd", "service", "start"]
    environment_variables(
      "BREW_APP_BIN_PATH" => "#{bin}",
      "BREW_APP_OPT_HOME" => "#{opt_prefix}",
      "BREW_PREFIX" => "#{HOMEBREW_PREFIX}"
    )
    keep_alive true
    error_log_path "#{var}/log/portola.app/portd.err.log"
    process_type :interactive
    working_dir opt_prefix
  end
end
